### ISSUE TITLE
Advice Migrating To ROS2?

### ISSUE THREAD

**Issue by slowrunner** [ros-gopigo/gopigo3_node#10]
I am starting a migration of this gopigo3_node to ROS2.

Q: Your thoughts on changing the ROS node to leave power management to the platform's gpg3_power.service and only publish the power pin status, (or leaving it to gpg3_power.service to manage the pin state, but continue to provide the power_off ROS service as a second way to shutdown the platform.)  

Reasoning: I have platform based battery level safety shutdown and a low battery level "WiFi LED" flasher to warn when 10-25 minutes of battery remain, and use gpg3_power.service as DI/MR intended.

Q: Anything you would have done different?

**Comment by christianrauch** [comment]
The idea with the ROS services was that you don't have to ssh into the robot to power the motors on/off. You should still be able to access the GPIO pints outside of the ROS node for custom scripts and services.

If you want to stick with the Python API, then I think porting this to ROS2 should be fairly easy. If you go with the C API, then I would make sure to implement every node as `rclcpp::Node` so that they can be loaded into the same process (similar to the ROS1 nodelets).

If you want, I can add your ROS2 node to this `ros-gopigo` group and make you a maintainer. I am not using the GoPiGo anymore (but I still have it around in case someone really needs me to test something). So if you are actively using the GoPiGo, you would be a much better maintainer :-).

**Comment by slowrunner** [comment]
>I can add your ROS2 node to this ros-gopigo group

Thanks, but as a ROS2 noob, I don't want to over-represent my dabbling.
